name: Entrega continua

on:
  workflow_call:

jobs:

  ECS:
    runs-on: ubuntu-latest
    steps:
      - name: Configurando Credenciais da AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Obtendo arquivo da tarefa
        run: aws ecs describe-task-definition --task-definition Go --query taskDefinition > task-definition.json
      
      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: Go
          image: ctiagosantos/go_ci:main
          environment-variables: |
            HOST=${{ secrets.DBHOST }}
            USER=${{ secrets.DBUSER }}
            PASSWORD=${{ secrets.DBPASSWORD }}
            DBNAME=${{ secrets.DBNAME }}
            DBPORT=${{ secrets.DBPORT }}
            PORT=8000
