name: Kubernetes

on:
  workflow_call:

jobs:

  EKS:
    runs-on: ubuntu-latest
    steps:
      - name: Configurando Credenciais da AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

    
      - run: git clone https://github.com/eutiagosantos/infra-CI-Kubernetes.git
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
      # iniciando o terraform
      - run: terraform -chdir=infra-CI-Kubernetes/env/Homolog init  

      - run: terraform -chdir=infra-CI-Kubernetes/env/Homolog apply -auto-approve  
