name: Go

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:

  test:
    runs-on: ${{ matrix.os }}
    env:
      HOST: localhost
      DBPORT: 5432
      USER: root
      PASSWORD: root
      DBNAME: root
    strategy:
      matrix:
        go_version: [">=1.20"]
        os: ["ubuntu-latest", "ubuntu-24.04"]
    steps:
    - uses: actions/checkout@v4
  
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go_version }}

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Build-DB
      run: docker-compose build

    - name: Create-DB
      run: docker-compose up -d
    
    - name: Test
      run: go test -v main_test.go

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: go build -v main.go

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.0
      with:
        # Artifact name
        name: programa
        # A file, directory or wildcard pattern that describes what to upload
        path: main
          
  docker:
    needs: build
    uses: ./.github/workflows/Docker.yml
    secrets: inherit
  
  # ec2:
  #   needs: build
  #   uses: ./.github/workflows/EC2.yml
  # # secrets: inherit
  
  # ECS:
  #     needs: docker
  #     uses: ./.github/workflows/ECS.yml
  #     secrets: inherit

  # LoadTest:
  #     needs: docker
  #     if: ${{ github.ref_name == 'Homolog' }}
  #     uses: ./.github/workflows/LoadTest.yml
  #     secrets: inherit

  EKS:
      needs: docker
      uses: ./.github/workflows/EKS.yml
      secrets: inherit
